# Generated by Django 4.1.7 on 2023-02-26 23:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='devices')),
                ('model', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('register_date', models.DateField(default=datetime.date.today)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
